[colors]
ansi = [
    '#d3dbd9',
    '#750000',
    '#006500',
    '#5f4602',
    '#353362',
    '#553372',
    '#35485e',
    '#000f0f'
]
brights = [
    '#d3dbd9',
    '#750000',
    '#006500',
    '#5f4602',
    '#353362',
    '#553372',
    '#35485e',
    '#000f0f'
]
cursor_bg = '#10600b'
cursor_border = '#10600b'
cursor_fg = '#e8f0e9'
background = '#e8f0e9'
foreground = '#000f0f'
selection_bg = '#94c2bf'
selection_fg = '#000f0f'

[metadata]
name = 'Doric-Wind'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-wind.toml'
