[colors]
ansi = [
    '#404240',
    '#ef6560',
    '#3fb83f',
    '#d4aa02',
    '#37aff6',
    '#d38faf',
    '#6fc5ef',
    '#cfdfd5'
]
brights = [
    '#808f80',
    '#ff778f',
    '#00c089',
    '#cfc04f',
    '#32cfef',
    '#af9fff',
    '#5dc0aa',
    '#8fcfaf'
]
cursor_bg = '#35f038'
cursor_border = '#35f038'
cursor_fg = '#cfdfd5'
background = '#111111'
foreground = '#cfdfd5'
selection_bg = '#3a3027'
selection_fg = '#cfdfd5'

[metadata]
name = 'Ef-Bio'
author = "anhsirk0"
origin_url = "https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-bio-theme.el"
