[colors]
ansi = [
    '#f5e9cb',
    '#ba2d2f',
    '#007a0a',
    '#a26310',
    '#375cc6',
    '#aa3e74',
    '#3f60af',
    '#484431'
]
brights = [
    '#c7b7a6',
    '#c02945',
    '#008250',
    '#946830',
    '#265fbf',
    '#6448ca',
    '#0f708a',
    '#68708a'
]
cursor_bg = '#a07f00'
cursor_border = '#a07f00'
cursor_fg = '#fff6d8'
background = '#fff6d8'
foreground = '#484431'
selection_bg = '#f0d4d8'
selection_fg = '#484431'

[metadata]
name = 'Ef-Melissa-Light'
author = 'anhsirk0'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-melissa-light-theme.el'
