[colors]
ansi = [
    '#cfb3c4',
    '#d3303a',
    '#217a3c',
    '#a45f22',
    '#375ce6',
    '#ba35af',
    '#1f6fbf',
    '#4f4073'
]
brights = [
    '#786e74',
    '#d50f7f',
    '#007f68',
    '#b65050',
    '#065fff',
    '#8e44f3',
    '#0f7b8f',
    '#af4988'
]
cursor_bg = '#cf0090'
cursor_border = '#cf0090'
cursor_fg = '#4f4073'
background = '#fff2f3'
foreground = '#4f4073'
selection_bg = '#eecfff'
selection_fg = '#4f4073'

[metadata]
name = 'Ef-Summer'
author = "anhsirk0"
origin_url = "https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-summer-theme.el"
