[colors]
ansi = [
    '#221920',
    '#ef6360',
    '#0faa26',
    '#bf9032',
    '#3f95f6',
    '#d369af',
    '#4fbaef',
    '#d0d0d0'
]
brights = [
    '#4b3f47',
    '#fe5a7a',
    '#00a692',
    '#df8a5a',
    '#029fff',
    '#af85ff',
    '#1dbfcf',
    '#857f8f'
]
cursor_bg = '#f0af7f'
cursor_border = '#f0af7f'
cursor_fg = '#130911'
background = '#130911'
foreground = '#d0d0d0'
selection_bg = '#3f2f40'
selection_fg = '#d0d0d0'

[metadata]
name = 'Ef-Symbiosis'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/ef-symbiosis.toml'
