[colors]
ansi = [
    '#ebe7f1',
    '#c3303a',
    '#057800',
    '#a45f22',
    '#375cd6',
    '#ad45ba',
    '#1f6fbf',
    '#4f3363'
]
brights = [
    '#c3c0c9',
    '#c01f5f',
    '#007f6f',
    '#b65050',
    '#065fbf',
    '#705ae3',
    '#0f7a9d',
    '#786e74'
]
cursor_bg = '#4f45ff'
cursor_border = '#4f45ff'
cursor_fg = '#f8f5ff'
background = '#f8f5ff'
foreground = '#4f3363'
selection_bg = '#eed0ff'
selection_fg = '#4f3363'

[metadata]
name = 'Ef-Trio-Light'
author = 'anhsirk0'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-trio-light-theme.el'
