[colors]
ansi = [
    '#282026',
    '#cf4f5f',
    '#2fa526',
    '#c48702',
    '#379cf6',
    '#b0648f',
    '#3fafcf',
    '#dfd0d5'
]
brights = [
    '#554f4f',
    '#d24f7f',
    '#00b066',
    '#df8f6f',
    '#029fff',
    '#a6699f',
    '#4fafaf',
    '#908890'
]
cursor_bg = '#fd3333'
cursor_border = '#fd3333'
cursor_fg = '#15050f'
background = '#15050f'
foreground = '#dfd0d5'
selection_bg = '#293140'
selection_fg = '#dfd0d5'

[metadata]
name = 'Ef-Tritanopia-Dark'
author = 'anhsirk0'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-tritanopia-dark-theme.el'
