[colors]
ansi = [
    '#353554',
    '#ef6560',
    '#6aad0f',
    '#c48052',
    '#6a9fff',
    '#d369af',
    '#6fafdf',
    '#807c9f'
]
brights = [
    '#807c9f',
    '#f47359',
    '#29a444',
    '#df9080',
    '#3f95f6',
    '#e580e0',
    '#4fbaef',
    '#b8c6d5'
]
cursor_bg = '#e580e0'
cursor_border = '#e580e0'
cursor_fg = '#b8c6d5'
background = '#0f0b15'
foreground = '#b8c6d5'
selection_bg = '#342464'
selection_fg = '#b8c6d5'

[metadata]
name = 'Ef-Winter'
author = "anhsirk0"
origin_url = "https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-winter-theme.el"
